receivers:
  otlp:
    protocols:
      grpc:

exporters:
  file:
    path: "/etc/output/corporate-variableincome-observability-logs.json"

processors:
  batch:

service:
  pipelines:
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [file]
