services:
  corporate-variableincome-messenger-persistence:
    image: confluentinc/cp-zookeeper:7.6.0
    container_name: corporate-variableincome-messenger-persistence
    ports:
      - 2181:2181
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    volumes:
      - corporate-variableincome-messenger-persistence-data:/var/lib/zookeeper
    networks:
      - corporate-variableincome-messenger

  corporate-variableincome-messenger-broker:
    image: confluentinc/cp-kafka:7.6.0
    container_name: corporate-variableincome-messenger-broker
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: corporate-variableincome-messenger-persistence:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
    volumes:
      - corporate-variableincome-messenger-broker-data:/var/lib/kafka
    depends_on:
      - corporate-variableincome-messenger-persistence
    networks:
      - corporate-variableincome-messenger

networks:
  corporate-variableincome-messenger:
    name: corporate-variableincome-messenger
    driver: bridge

volumes:
    corporate-variableincome-messenger-broker-data:
    corporate-variableincome-messenger-persistence-data: