// <auto-generated />
using System;
using Corporate.VariableIncome.Infrascructure.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Corporate.VariableIncome.Infrascructure.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20250606193122_add_table_position_snapshots_on_database")]
    partial class add_table_position_snapshots_on_database
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Corporate.VariableIncome.Domain.BoundedContexts.AssetContext.Entities.Asset", b =>
                {
                    b.Property<Guid>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("UUID")
                        .HasColumnName("idasset")
                        .IsFixedLength();

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("VARCHAR")
                        .HasColumnName("code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("VARCHAR")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_asset_id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("uk_asset_code");

                    b.HasIndex("Id")
                        .IsUnique()
                        .HasDatabaseName("uk_asset_id");

                    b.ToTable("assets", (string)null);
                });

            modelBuilder.Entity("Corporate.VariableIncome.Domain.BoundedContexts.OperationContext.Entities.Operation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("UUID")
                        .HasColumnName("idoperation")
                        .IsFixedLength();

                    b.Property<Guid>("AssetId")
                        .HasMaxLength(36)
                        .HasColumnType("UUID")
                        .HasColumnName("asset_id")
                        .IsFixedLength(false);

                    b.Property<decimal>("BrokerageFee")
                        .HasColumnType("DECIMAL(3,2)")
                        .HasColumnName("brokerage_fee")
                        .IsFixedLength(false);

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("TIMESTAMPTZ")
                        .HasColumnName("operation_date")
                        .IsFixedLength();

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER")
                        .HasColumnName("quantity")
                        .IsFixedLength(false);

                    b.Property<decimal>("UnitaryPrice")
                        .HasColumnType("DECIMAL(18,2)")
                        .HasColumnName("unitary_price")
                        .IsFixedLength(false);

                    b.Property<Guid>("UserId")
                        .HasMaxLength(36)
                        .HasColumnType("UUID")
                        .HasColumnName("user_id")
                        .IsFixedLength(false);

                    b.HasKey("Id")
                        .HasName("pk_operation_id");

                    b.HasIndex("AssetId")
                        .HasDatabaseName("idx_operation_asset_id");

                    b.HasIndex("DateTime")
                        .IsDescending()
                        .HasDatabaseName("idx_operation_date_time");

                    b.HasIndex("Id")
                        .IsUnique()
                        .HasDatabaseName("uk_operation_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("idx_operation_user_id");

                    b.ToTable("operations", (string)null);
                });

            modelBuilder.Entity("Corporate.VariableIncome.Domain.BoundedContexts.PositionContext.Entities.PositionSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("UUID")
                        .HasColumnName("idpositionsnapshot")
                        .IsFixedLength();

                    b.Property<Guid>("AssetId")
                        .HasMaxLength(36)
                        .HasColumnType("UUID")
                        .HasColumnName("asset_id")
                        .IsFixedLength();

                    b.Property<decimal>("AveragePrice")
                        .HasColumnType("DECIMAL(18,2)")
                        .HasColumnName("average_price")
                        .IsFixedLength(false);

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("TIMESTAMP")
                        .HasColumnName("snapshot_datetime")
                        .IsFixedLength(false);

                    b.Property<decimal>("ProftAndLoss")
                        .HasColumnType("DECIMAL(20,4)")
                        .HasColumnName("proft_and_loss")
                        .IsFixedLength(false);

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER")
                        .HasColumnName("quantity")
                        .IsFixedLength(false);

                    b.Property<Guid>("UserId")
                        .HasMaxLength(36)
                        .HasColumnType("UUID")
                        .HasColumnName("user_id")
                        .IsFixedLength();

                    b.HasKey("Id")
                        .HasName("pk_position_snapshot_id");

                    b.HasIndex("Id")
                        .IsUnique()
                        .HasDatabaseName("uk_position_snapshot_id");

                    b.HasIndex("UserId");

                    b.HasIndex("AssetId", "UserId")
                        .HasDatabaseName("idx_position_snapshot_asset_user");

                    b.ToTable("position_snapshots", (string)null);
                });

            modelBuilder.Entity("Corporate.VariableIncome.Domain.BoundedContexts.UserContext.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("UUID")
                        .HasColumnName("iduser")
                        .IsFixedLength();

                    b.Property<decimal>("BrokerageFee")
                        .HasColumnType("DECIMAL(9, 8)")
                        .HasColumnName("brokerage_fee")
                        .IsFixedLength(false);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("VARCHAR")
                        .HasColumnName("email")
                        .IsFixedLength(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("VARCHAR")
                        .HasColumnName("name")
                        .IsFixedLength(false);

                    b.HasKey("Id")
                        .HasName("pk_user_id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("uk_user_email");

                    b.HasIndex("Id")
                        .IsUnique()
                        .HasDatabaseName("uk_user_id");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Corporate.VariableIncome.Domain.BoundedContexts.OperationContext.Entities.Operation", b =>
                {
                    b.HasOne("Corporate.VariableIncome.Domain.BoundedContexts.AssetContext.Entities.Asset", "Relationship1AssetNOperations")
                        .WithMany("Operations")
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_operation_asset_id");

                    b.HasOne("Corporate.VariableIncome.Domain.BoundedContexts.UserContext.Entities.User", "Relationship1UserNOperations")
                        .WithMany("Operations")
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_operation_user_id");

                    b.Navigation("Relationship1AssetNOperations");

                    b.Navigation("Relationship1UserNOperations");
                });

            modelBuilder.Entity("Corporate.VariableIncome.Domain.BoundedContexts.PositionContext.Entities.PositionSnapshot", b =>
                {
                    b.HasOne("Corporate.VariableIncome.Domain.BoundedContexts.AssetContext.Entities.Asset", "Relationship1AssetNPositionSnapshots")
                        .WithMany("PositionSnapshots")
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_position_snapshot_asset_id");

                    b.HasOne("Corporate.VariableIncome.Domain.BoundedContexts.UserContext.Entities.User", "Relationship1UserNPositionSnapshots")
                        .WithMany("PositionSnapshots")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_position_snapshot_user_id");

                    b.Navigation("Relationship1AssetNPositionSnapshots");

                    b.Navigation("Relationship1UserNPositionSnapshots");
                });

            modelBuilder.Entity("Corporate.VariableIncome.Domain.BoundedContexts.AssetContext.Entities.Asset", b =>
                {
                    b.Navigation("Operations");

                    b.Navigation("PositionSnapshots");
                });

            modelBuilder.Entity("Corporate.VariableIncome.Domain.BoundedContexts.UserContext.Entities.User", b =>
                {
                    b.Navigation("Operations");

                    b.Navigation("PositionSnapshots");
                });
#pragma warning restore 612, 618
        }
    }
}
