// <auto-generated />
using System;
using Corporate.VariableIncome.Infrascructure.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Corporate.VariableIncome.Infrascructure.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20250606044021_add_table_users_on_database")]
    partial class add_table_users_on_database
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Corporate.VariableIncome.Domain.BoundedContexts.UserContext.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("UUID")
                        .HasColumnName("iduser")
                        .IsFixedLength();

                    b.Property<decimal>("BrokerageFee")
                        .HasColumnType("DECIMAL(9, 8)")
                        .HasColumnName("brokerage_fee")
                        .IsFixedLength(false);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("VARCHAR")
                        .HasColumnName("email")
                        .IsFixedLength(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("VARCHAR")
                        .HasColumnName("name")
                        .IsFixedLength(false);

                    b.HasKey("Id")
                        .HasName("pk_user_id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("uk_user_email");

                    b.HasIndex("Id")
                        .IsUnique()
                        .HasDatabaseName("uk_user_id");

                    b.ToTable("users", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
